name: Zotero to Readwise Automation

on:
  push:
    branches:
      - master
  schedule:
    #Check https://crontab.guru/
    - cron: "0 10 * * *"  # 每天 UTC 10:00（台灣時間 18:00）
    - cron: "0 22 * * *"  # 每天 UTC 22:00（台灣時間 06:00）

jobs:
  zotero-to-readwise-automation:
    runs-on: ubuntu-latest
    steps:
      - name: 🍽️ Checkout the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: 🐍 Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 💿 Install Zotero2Readwise Python package
        run: |
            pip install zotero2readwise
            pip install pyzotero==1.5.5

      - name: 📥 Download the Python script needed for automation
        run:  curl https://raw.githubusercontent.com/e-alizadeh/Zotero2Readwise/master/zotero2readwise/run.py -o run.py
      
      - name: 🚀 Run Automation
        run: python run.py ${{ secrets.READWISE_TOKEN }} ${{ secrets.ZOTERO_KEY }} ${{ secrets.ZOTERO_ID }}
